// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Table("Livro_Cliente_Emprestimo")]
public partial class LivroClienteEmprestimo
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("lceIdLivro")]
    public int? LceIdLivro { get; set; }

    [Column("lceIdCliente")]
    public int? LceIdCliente { get; set; }

    [Column("lceDataEmprestimo", TypeName = "datetime")]
    public DateTime? LceDataEmprestimo { get; set; }

    [Column("lceDataDevolucao", TypeName = "datetime")]
    public DateTime? LceDataDevolucao { get; set; }

    [Column("lceEntrega")]
    public int? LceEntrega { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("LivroClienteEmprestimo")]
    public virtual Livro Id1 { get; set; }

    [ForeignKey("Id")]
    [InverseProperty("LivroClienteEmprestimo")]
    public virtual Cliente IdNavigation { get; set; }
}