// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace LivrariaControleEmprestimo.DATA.Models;

[Keyless]
public partial class VwLivroClienteEmprestimo
{
    [Required]
    [Column("cliNome")]
    [StringLength(200)]
    [Unicode(false)]
    public string CliNome { get; set; }

    [Required]
    [Column("livroNome")]
    [StringLength(50)]
    [Unicode(false)]
    public string LivroNome { get; set; }

    [Column("id")]
    public int Id { get; set; }

    [Column("lceIdLivro")]
    public int LceIdLivro { get; set; }

    [Column("lceIdCliente")]
    public int LceIdCliente { get; set; }

    [Column("lceDataEmprestimo", TypeName = "datetime")]
    public DateTime LceDataEmprestimo { get; set; }

    [Column("lceDataDevolucao", TypeName = "datetime")]
    public DateTime LceDataDevolucao { get; set; }

    [Column("lceEntrega")]
    public int LceEntrega { get; set; }
}